baseURL = "https://loyolaaiclub.github.io"
title = "Tella"
author = "Loyola AI Club"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['Speakers']

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "LAIC Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Loyola AI Club"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Loyola AI Club"
    meta_og_type = "website"
    meta_og_url = "https://loyolaaiclub.github.io"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "Speakers"
    name = "Speakers"
    url = "/speakers/"
    weight = 2

  [[menu.main]]
    identifier = "Workshops"
    name = "Workshops"
    url = "/workshops/"
    weight = 3

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/projects/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
